{"name": "密码错误的场景", "status": "passed", "description": "我们的第一个登录小程序", "attachments": [{"name": "接口地址", "source": "8c6455f5-674a-45a6-bff2-c62268fb9c36-attachment.attach"}, {"name": "接口参数", "source": "6e0c6c83-bd87-4a77-9081-1360b9beb1e4-attachment.attach"}, {"name": "响应结果", "source": "aa150841-d262-4efb-9536-6403c5f3a033-attachment.attach"}, {"name": "log", "source": "ed64cca9-420d-4b45-ba84-09b5d7217a90-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "78cf3342-04ec-48f4-b77d-dc4d56bb6f27-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "<day15.test_excel_data.excel_test02.CaseData object at 0x0000028D2F186CC0>"}], "start": 1660463253722, "stop": 1660463253791, "uuid": "f824ea70-e1b0-4ef7-83de-fa16c4b5812e", "historyId": "0a5850f360156f3c5d6052f500c596eb", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "登录模块的子模块"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31HM1IE"}, {"name": "thread", "value": "9324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}